-- CRIAR BASE DE DADOS

CREATE DATABASE BD_FACULDADE_JONATAS;

-- SELECIONAR A BASE DE DADOS

USE BD_FACULDADE_JONATAS;

-- CRIAR TABELA 

CREATE TABLE ALUNO (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	NOME VARCHAR(100) NOT NULL,
	IDADE INT NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
);

-- SELECIONAR A TABELA
SELECT * FROM ALUNO;